version: '3.1'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_HOSTNAME: db
      MONGO_PORT: $MONGO_PORT
      MONGO_DB: $MONGO_DB
    ports:
      - "8082:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: