version: '3.3'

services:
  node:
    build: .
    working_dir: /app
    ports:
        - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker-entrypoint-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
